# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Build
      run: go build -v ./...

    - name: Lint
      run: go vet ./...

    - name: Build Docker image
      #run: go test -v ./...
      run: docker-compose -f ./docker-compose.yml build

    # cicd_apiフォルダ内にあるdocker-composeの実行
    - name: UnitTEST DB UP
      run: docker-compose -f ./docker-compose.yml up -d

    # テスト実行
    - name: UnitTEST
      run: go test -cover ./... -coverprofile=./coverage/cover.out

    # テスト結果をカバレッジレポートに変換
    - name: Convert coverage to Cobertura
      run: go tool cover -html=./coverage/cover.out -o ./coverage/cover.html